language: C
os: linux
dist: trusty
sudo: true
compiler: gcc


before_install:
   - sudo apt-get update -qq
   - sudo apt-get install flex bison git

script:
	- git clone "https://github.com/samtools/htslib.git" && cd htslib && make lib-shared
    - make bcfselectgt test HTSLIB=htslib
